---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    app.openshift.io/vcs-uri: git@github.com:sshaaf/kantra-rules-gen.git
    app.quarkus.io/quarkus-version: 3.18.4
    app.quarkus.io/commit-id: 74087b74d8160c7b44db4539483985601a944aba
    app.quarkus.io/vcs-uri: https://github.com/sshaaf/kantra-rules-gen.git
    app.quarkus.io/build-timestamp: 2025-04-22 - 01:26:19 +0000
  labels:
    app.kubernetes.io/name: kantra-rules-gen
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app.kubernetes.io/managed-by: quarkus
    app.openshift.io/runtime: quarkus
  name: kantra-rules-gen
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/name: kantra-rules-gen
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  name: view-secrets
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: kantra-rules-gen
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  name: kantra-rules-gen-view-secrets
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: view-secrets
subjects:
  - kind: ServiceAccount
    apiGroup: ""
    name: kantra-rules-gen
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: kantra-rules-gen
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  name: kantra-rules-gen-view
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: view
subjects:
  - kind: ServiceAccount
    name: kantra-rules-gen
---
apiVersion: v1
kind: Service
metadata:
  name: kantra-rules-gen-service
spec:
  selector:
    app: kantra-rules-gen
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: kantra-rules-gen-route
spec:
  to:
    kind: Service
    name: kantra-rules-gen-service
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
---
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: kantra-rules-gen
  labels:
    app: kantra-rules-gen
spec:
  replicas: 1
  selector:
    app: kantra-rules-gen
  strategy:
    type: Rolling # Use default rolling update parameters
  template:
    metadata:
      labels:
        app: kantra-rules-gen
    spec:
      containers:
        - name: kantra-rules-gen-app
          image: quay.io/sshaaf/kantra-rules-gen:latest
          envFrom:
            - configMapRef:
                name: my-quarkus-app-prod-config
            - secretRef:
                name: app-credentials
          ports:
            - containerPort: 8080
              protocol: TCP
          volumeMounts:
            - mountPath: /deployments/config
              name: es-cert-volume
              readOnly: true
      serviceAccountName: kantra-rules-gen
  triggers:
    - type: ConfigChange # Redeploy when DC changes